config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts

  match '/login', to: 'users#login', as: 'login', via: [:get, :post]
  get '/logout', to: 'users#logout', as: 'logout'
  post '/add_comment', to: 'posts#add_comment', as: 'add_comment'

  namespace :api do
    namespace :v1 do
      get '/posts', to: 'posts#index'
      get '/posts/:id', to: 'posts#show'
      post '/posts', to: 'posts#create'
      post '/posts/:id', to: 'posts#update'
      delete '/posts/:id', to: 'posts#destroy'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', primary_key: :id, foreign_key: :author_id
  has_many :comments, as: :commentable
  mount_base64_uploader :image, ImageUploader

  def self.build_from_json(json_params)
    post_params = get_post_params(json_params)
    author = User.find_by(email_address: json_params['post']['author_email_address'])
    post_id = json_params['post']['id']
    post = Post.find_by(api_id: post_id) if post_id.present?
    post ||= Post.new
    post.assign_attributes(post_params)
    post.author = author
    post.comments.destroy_all
    json_params['post']['comments'].each do |comment|
      user = User.find_by(email_address: comment['user_email_address'])
      post.comments.build({ content: comment['content'], commentable: post, user: user })
    end
    api_id = Post.maximum(:id) || 0
    post.api_id = "PS#{api_id.next}" unless post.api_id.present?
    post
  end

  def self.get_post_params(json_params)
    json_params['post'].permit(:title, :content, :image)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, class_name: 'Post', primary_key: :id, foreign_key: :author_id, dependent: :destroy

  def self.authenticate(options)
    user = find_by_email_address(options[:email_address])
    return nil unless user&.authenticate(options[:password])

    user
  end

  def authenticate(password)
    password_hash == User.encrypt(password)
  end

  def self.encrypt(password)
    Digest::SHA1.hexdigest(password.to_s)
  end
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ApiController < ApplicationController
      before_action :check_basic_auth
      skip_before_action :verify_authenticity_token

      private

      def check_basic_auth
        unless request.authorization.present?
          head :unauthorized
          return
        end
        authenticate_with_http_basic do |email, password|
          user = User.find_by(email_address: email.downcase)
          if user&.authenticate(password)
            @current_user = user
          else
            head :unauthorized
          end
        end
      end

      attr_reader :current_user
    end
  end
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < Api::V1::ApiController
      before_action :load_post, only: %i[update destroy show]

      def index
        @posts = Post.includes(:comments)
      end

      def create
        @post = Post.build_from_json(params)
        if @post.valid?
          @post.save
          render json: { success: true, status: 200, id: @post.api_id }
        else
          render json: { success: false, status: 200, error_message: @post.errors.messages }
        end
      end

      def show; end

      def update
        @post = Post.build_from_json(params)
        if @post.valid?
          @post.save
          render 'show'
        else
          render json: { success: false, status: 200, error_message: @post.errors.messages }
        end
      end

      def destroy
        @post.destroy
        render json: { success: true, status: 200 }
      end

      private

      def load_post
        @post = Post.find_by(api_id: params[:id])
        unless @post
          render json: { success: false, status: 200, error_message: "No post exist with ID #{params[:id]}" } and return
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentication_controller.rb
# frozen_string_literal: true

class AuthenticationController < ApplicationController
  protect_from_forgery with: :exception
  before_action :verify_login
  before_action :current_user

  def login_as(user)
    raise 'No user passed' unless user

    set_current_user(user)
  end

  def set_current_user(user)
    reset_session
    session['user_id'] = user.id
    @current_user = user
  end

  def current_user
    user = nil
    @current_user = (
      user = User.find_by_id(session['user_id']) if session['user_id']
      user
    )
  end

  def verify_login
    unless current_user
      flash[:error] = 'You must login to access this page'
      redirect_to '/login'
    end
  end

  def reset_user_session
    reset_session
    redirect_to '/login'
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < AuthenticationController
  skip_before_action :verify_login, only: %i[index show]
  before_action :load_post, only: %i[update show edit destroy add_comment]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10)
  end

  def show
    if stale?(last_modified: @post.updated_at)
      respond_to do |format|
        format.html
        format.json { render json: @post }
      end
    end
    expires_in 1.day, :public => true
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'The post was created!'
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:success] = 'Update successful'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post destroyed'
    redirect_to root_path
  end

  def add_comment
    Comment.create({ content: params[:comment], commentable: @post, user: @current_user })
    redirect_to action: 'show', id: @post.id
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :author_id, :image)
  end

  def load_post
    @post = Post.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < AuthenticationController
  skip_before_action :verify_login, only: [:login]
  def login
    if request.get?
      if current_user
        flash[:notice] = 'You have already logged in'
        redirect_to '/'
        return
      end
    end
    if request.post?
      unless params[:user]
        flash[:error] = 'Invalid login'
        redirect_to '/login'
        return
      end
      user = User.authenticate(params[:user])
      unless user
        flash[:error] = 'Credentials are wrong'
        redirect_to '/login'
        return
      end
      login_as user
      redirect_to '/'
      nil
    end
  end

  def logout
    reset_session
    redirect_to '/login'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>  
  </head>

  <body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
      <a class="navbar-brand" href="#">Blog App</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
        </ul>
        <% if @current_user %>
          <%= form_tag('/logout', method: :get) do %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <button name="logout" type="submit" class="btn btn-outline-info my-2 my-sm-0">Logout</button>
          <% end %>
        <% end %>
      </div>
    </nav>
    <div class="container">
      <% unless flash[:success].blank? %>
        <div class="alert alert-success">
          <%= flash[:success] %>
        </div>
      <% end %>

      <% unless flash[:notice].blank? %>
        <div class="alert alert-primary">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% unless flash[:error].blank? %>
        <div class="alert alert-danger">
          <%= flash[:error] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <script type="text/javascript">
      <%= content_for :scripts %>
    </script>
  </body>
  
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <div >
  <%= f.label :title, :class => "font-weight-bold" %><br>
  </div>
  <div class="form-group">
  <%= f.text_field :title, placeholder: "Type the post title here", :class => "form-control" %><br>
  </div>
  <div>
  <%= f.label :content, :class => "font-weight-bold" %><br>
  </div>
  <div class="form-group">
  <%= f.text_area :content, placeholder: "Type the post tect here", :class => "form-control" %><br>
  </div>
  <div>
  <%= f.label :image, :class => "font-weight-bold" %><br>
  </div>
  <div class="form-group">
  <%= f.file_field :image, :class => "form-control-file col-sm-3 p-0"%><br>
  </div>
  <div class="form-group">
  <%= f.submit btn_label, :class => "btn btn-info" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="d-flex flex-column">
	<div class="align-self-end">
	  <%= link_to "Back", root_path, :class => "btn btn-info mt-2" %>
	</div>
	<div>
	  <%= render :partial => 'form', :locals => {:btn_label => "Update"} %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="d-flex flex-column">
	<div class="align-self-end">
		<%= link_to "Create Post", '/posts/new', :class => "btn btn-info mt-2" %>
	</div>
	<div>
		<% @posts.each do |post| %>
	     <h2><%= link_to post.title, post %></h2>
	     <p><%= truncate(post.content) %></p>
		<% end %>

		<%= will_paginate @posts %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="d-flex flex-column">
	<div class="align-self-end">
	  <%= link_to "Back", root_path, :class => "btn btn-info mt-2" %>
	</div>
	<div>
	  <%= render :partial => 'form', :locals => {:btn_label => "Create"} %>
	</div>
</div>

app/views/posts/show.html.erb
<div>
  <h1><%= @post.title %></h1>
  <h3><%= @post.author.name %></h3>
  <div>
    <p><%= @post.content %></p>
  </div>
  <div>
    <% if @post.image.present? %>
      <%= image_tag @post.image_url.to_s, alt: "Image", class: "img-fluid mb-5" %>
    <% end %>
  </div>

  <% if @current_user && @current_user == @post.author %>
    <% if @current_user == @post.author %>
  		<%= link_to "Edit", edit_post_path(@post), :class => "btn btn-primary mb-2" %>
  		<%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?"}, :class => "btn btn-danger mb-2" %>
  	<% end %>
  <% end %>
  <div>
    <label style="font-size: 30px;">Comments</label>
    <% @post.comments.each do |comment| %>
      <h6><%= comment.user.name %></h6>
      <p><%= comment.content %></p>
    <% end %>
  </div>

  <% if @current_user && @current_user == @post.author %>
    <div class="text-right mb-2">
      <button id="add_comment" class="btn btn-info">Add Comments</button>
    </div>
  <% end %>

  <%= form_tag add_comment_path, :id => 'add_comment_form', :method => 'post' do %>
    <%= hidden_field_tag "id", @post.id %>
    <div class="form-group">
      <%= text_area_tag 'comment', nil, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= submit_tag 'Save', :class => "btn btn-dark"%>
    </div>
  <% end %>
</div>
<% content_for :scripts do %>

  jQuery(function($) {
    $(document).ready(function(){
 			$('#add_comment_form').hide();
    });
  	$('#add_comment').on('click', function(){
  		$('#add_comment_form').show();
    });
  })
    
<% end %>
  

app/views/users/login.html.erb
<div class="m-5">
  <%= form_tag('/login', :class => 'form-control-lg') do %>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div class="form-group row">
      <label class=" col-sm-2">Email Address:</label>
      <div class="col-sm-4 ">
        <%= text_field_tag 'user[email_address]', nil, :class => 'form-control', :required => true %>
      </div>
    </div>
    <div class="form-group row">
      <label class=" col-sm-2">Password:</label>
      <div class="col-sm-4 ">
        <%= password_field_tag 'user[password]', nil, :class => 'form-control', :required => true %>
      </div>
    </div>
    <div class="form-group">
      <button name="login" type="submit" class="btn btn-primary">Login</button>
    </div>
  <% end %>
</div>